export enum IconList {
  CLOSE = "close",
  REMOVE = "close",
  DELETE = "close",
  NEW = "new",
  ADD = "add",
  EDIT = "edit",
  ARROW_LEFT = "arrow-left",
  ARROW_UP = "arrow-up",
  ARROW_RIGHT = "arrow-right",
  ARROW_DOWN = "arrow-down",
  FLAG_UK = "flag-uk",
  FLAG_NL = "flag-nl",
  COMPANY = "company",
  HOME = "home",
  FILE = "file",
}
